### ISSUE TITLE
[Blender 4.3.1 (hash 33d812126174 built 2024-12-10 10:08:19)] Invalid argument

### ISSUE THREAD

**Issue by wikijm** [Aimi-no/BlenderGLB2OBJ#1]
Hi @zderaann 

Thanks a lot for your script, it is exactly what I'm looking for transforming .glb files downloaded from IKEA 😄 

Sadly, I'm facing an error, as described below

Script folder path:              C:\tools\BlenderGLB2OBJ
Execution commandline:    "c:\Program Files\Blender Foundation\Blender 4.3\blender.exe" --background --python ./glb2obj.py -- ./
Result:
```bash
Blender 4.3.1 (hash 33d812126174 built 2024-12-10 10:08:19)
args parsed
deleted startup objects
walking folder
Found GLB file
20:12:13 | INFO: Data are loaded, start creating Blender stuff
20:12:13 | INFO: Blender create Mesh node Mesh_0
20:12:13 | INFO: Draco Decoder: Decode primitive Mesh_0
DracoDecoder | Decoded 16072 vertices, 45072 indices
20:12:13 | INFO: glTF import finished in 0.05s
Saving image material0_basecolor
Invalid argument
Error: Could not write image: Invalid argument
Error: Image 'material0_basecolor' could not be saved to ''
Traceback (most recent call last):
  File "c:\tools\BlenderGLB2OBJ\glb2obj.py", line 99, in <module>
    register()
  File "c:\tools\BlenderGLB2OBJ\glb2obj.py", line 51, in register
    im.save()
RuntimeError: Error: Could not write image: Invalid argument
Error: Image 'material0_basecolor' could not be saved to ''


Blender quit
```

Do you have an idea what's wrong?

**Comment by zderaann** [comment]
Hi, sorry for the late reply. Do you still face this issue? I can look into it, which model is making problems?

**Comment by wikijm** [comment]
Hi @zderaann 

Happy New Year 🥳 

No problem for the delay, we all have a life and you're already kind enough to share your work and answer to me 😉 

Yes, I'm still facing the issue.

Let's take an example: https://www.ikea.com/ch/en/p/kallax-shelving-unit-white-80275887/
With Firefox extension [Tampermonkey](https://www.tampermonkey.net/), I'm using [this script](https://github.com/apinanaivot/IKEA-3D-Model-Download-Button) to download a .glb file.

**Comment by wikijm** [comment]
[KALLAX shelving unit - white.zip](https://github.com/user-attachments/files/18342875/KALLAX.shelving.unit.-.white.zip)
